apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "admin"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
      initContainers:
      - name: init-mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        command: ["/bin/sh", "-c", "mysql -u root -p$MYSQL_ROOT_PASSWORD < /etc/mysql/init-scripts/message.sql"]
        volumeMounts:
        - name: init-scripts
          mountPath: /etc/mysql/init-scripts
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: init-scripts
        configMap:
          name: mysql-init-scripts